### ISSUE TITLE
Use Weblate for translation

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#120]
It would be great to host our own instance for translation for all uCoin project: [uCoin](https://github.com/ucoin-io/ucoin), [CuteCoin](https://github.com/ucoin-io/cutecoin), [ucoin-android-app](https://github.com/ucoin-io/ucoin-android-app), [RTM](https://github.com/vtexier/theorie-relative-de-la-monnaie) with the free [Weblate](http://weblate.org/en/).

**Comment by c-geek** [comment]
Done: http://weblate.ucoin.io
