### ISSUE TITLE
Bug with tx/history, probably due to large requests

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#122]
Just got a bug today with tx/history request : 

http://metab.ucoin.io:9201/tx/history/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU/blocks/0/20353

Look for the hash "B94E7F6289D4C54EC9D1126484981EE993E1B0A6" : all data are corrupted after this block.

EDIT : Well it happens for shorter ranges too : 
http://metab.ucoin.io:53674/tx/history/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU/blocks/0/100

**Comment by c-geek** [comment]
Yep, this is known bug. Have to fix it :)

**Comment by c-geek** [comment]
No more present in current DEV version, but it is required to replay the indexation process to fix the problem.

This issue will be closed when this reindexing tool will be added.
