### ISSUE TITLE
Add options to automatically configure IPv4/6

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#140]
Could you add options to automatically configure `--ipv4 `, `--ipv6 `, `--remote4` and `--remote4` for YunoHost package. I am asking this because I can't do it graphically within a Shell script.
Actually, I'm [configuring uCoin node that way](https://github.com/ucoin-io/ucoin_ynh/blob/master/scripts/install#L32) and I'm getting issue to retrive [IPv4](https://github.com/ucoin-io/ucoin_ynh/blob/master/scripts/install#L4-L5) with this Shell script. Pipes are not working well within YunoHost core Python apparently :smile_cat:

**Comment by c-geek** [comment]
The problem with "automatically" is that we do not know very much about "where" we are.

I will see what I can do, since the wizard already guesses almost everything - but he can be wrong!

**Comment by c-geek** [comment]
Sure, let's go on a "--autoconf" option :smiley_cat:

**Comment by c-geek** [comment]
Is it easy for you to find the DNS name or provide it to the script ?

**Comment by M5oul** [comment]
Nice :cat:
Yep, I can easily [retrieve the domain name](https://github.com/ucoin-io/ucoin_ynh/blob/master/scripts/install#L6) where the package install uCoin node.
