### ISSUE TITLE
Use BitTorrent protocol to sync network

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#142]
When uCoin will be stronger, it could be cool if it manage BitTorrent protocol to sync. That way it could go faster to download long and massive blockchain. For instance, each turn a node create a torrent file containing latests blocks for every 1.000 blocks added. May be it is a waste of time trying implement that type of sync. It need to be well thought.

Here some projects using JavaScript implementations of BitTorrent protocol:
* [WebTorrent](https://github.com/feross/webtorrent)
* [JSTorrent web site](http://jstorrent.com/) / [GitHub](https://github.com/kzahel/jstorrent)

**Comment by c-geek** [comment]
The idea is good, but we won't be concerned by this before years. So I close the issue!
