### ISSUE TITLE
Error with tx_history : Missing tx or empty data

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#143]
Hi,

http://metab.ucoin.io:9201/tx/history/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU/blocks/21329/21428

I received a transaction on block 21330 : 
http://metab.ucoin.io/blockchain/Block/21330

**Comment by Insoleet** [comment]
Edited the bug analysis.

**Comment by c-geek** [comment]
Fixed in 0.12.
