### ISSUE TITLE
Error with code returned by certifiers-of

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#146]
Hello,

When requesting this URL with QNetworkManager : 
http://metab.ucoin.io:53674/wot/certifiers-of/J4t7PAdimfgiiTY2XFoM417k8X33sm1zdLn9rfAjN1aC

I get error "ProtocolInvalidOperationError". The error returned is not interpreted as an HTTP error, which means it's not a correct HTTP reply. I suppose it's because the URL should return Json data ( Content-Type : ""application/json"" ), but it returns raw text error : "No member matching this pubkey or uid".

Also, the status code returned is "error 400 : bad request" with Firefox. Shouldn't the URL returns a 404 anyway ?

**Comment by c-geek** [comment]
I've added another issue (#159) for error messages, but fixed the HTTP 400 code.
