### ISSUE TITLE
Change the "written" field of certifiers-of and certifiers-by for multibranch

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#151]
The "written" :"true" should change to the number of the block written, or null. Because we need to know when was the transaction written to be able to know if it is in the fork window or not.

**Comment by c-geek** [comment]
Done, Sir.

http://metab.ucoin.io/wot/certified-by/inso
http://metab.ucoin.io/wot/certifiers-of/inso

**Comment by Insoleet** [comment]
Great :+1:
