### ISSUE TITLE
Problem syncing

### ISSUE THREAD

**Issue by clehner** [ucoin-io/ucoin#155]
ucoind gets stuck syncing. I have tried removing `~/.config/ucoin/ucoin_default` and trying again but I get the same error.
```
$ bin/ucoind sync metab.ucoin.io 9201
```
```

Progress:

Download: [                    ] 0 %
Apply:    [                    ] 0 %

Status: Block 33 not found on DAL coreDal_32_00051981FE67A6FC20B4884460EE160170EEEE8C
All done.
```
It is the same if I use `--nocautious`
What does this error mean?

**Comment by c-geek** [comment]
You are on the master branch which is currently very unstable.

I am developing the multibranch feature, and you are facing a bug about it. This is the main bug I am trying to fix for mutibranch to work.

**Comment by c-geek** [comment]
This should be fixed now, even if we need deeper tests to confirm we have a satisfying behavior.

**Comment by clehner** [comment]
Ok I switched to 0.11.13 and then to master and it was working for a while. Then I stopped it and ran the command again and now it stops with:
```
Progress:

Download: [||||||||||||||||||||] 100 %
Apply:    [|||                 ] 15 %

Status: Fork 5045-000077BDD63EC95F5EBD897211FE14EBE83A2C75 already exists
All done.
```
Should I switch back to 11.13 or delete the data and restart the sync on master?

**Comment by c-geek** [comment]
So it's one of 2 options:

* you can use 0.11.13, which is working (but regularly forking as may have seen)
* you can use 0.12 (master), but you should use the following commands to sync:

    $ ucoind reset data
    $ ucoind sync metab.ucoin.io 9201 --nofork --nocautious
    $ ucoind config --forksize 10
    $ ucoind start

This way you will have a regular 0.12 ucoin node able to fork within a window of 10 blocks. But we are still experimenting this behavior :)

**Comment by clehner** [comment]
Ok thanks, I'm trying that now and it's working so far.

**Comment by c-geek** [comment]
I've made more tests and it seems that v0.12 is slow when started, I mean for receiving new blocks.
