### ISSUE TITLE
No signature in block 96 ?

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#158]
http://metab.ucoin.io:9201/blockchain/block/96
http://metab.ucoin.io:9212/blockchain/block/96

The raw document is missing a signature

**Comment by Insoleet** [comment]
Ok, my mistake. The difference is not the signature : 
https://www.diffchecker.com/utxzzuep

It only happens with the node 9201.

**Comment by c-geek** [comment]
If you have a look at source code of the above URIs (block/96), you can see that both results are identical.

I don't see what is your issue.
