### ISSUE TITLE
Transaction validated in multiple blocks

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#168]
So I sent a transaction to test tx appearing multiple times in cutecoin, with the commentary "test doublons" ...
So the tx is broadcasted to all nodes, and they are validating and registering the transaction multiple times in the blockchain ?!

http://metab.ucoin.io:9201/blockchain/block/32685
http://metab.ucoin.io:9201/blockchain/block/32686
http://metab.ucoin.io:30424/blockchain/block/32687

The inputs are the same for each transaction, so there is obviously a problem there.

**Comment by c-geek** [comment]
Ok this a multibranch issue, the node with v0.10.7 does not accept it.

**Comment by c-geek** [comment]
We have the same problem on block:

* http://metab.ucoin.io:9201/blockchain/block/32586
* http://metab.ucoin.io:9201/blockchain/block/32587

**Comment by c-geek** [comment]
Very stupid error ... this is why I definitely need to write more tests & keep old nodes to avoid regressions.

**Comment by Insoleet** [comment]
Well just don't forgot to write a test for this bug ;)
