### ISSUE TITLE
Behaviour for pubkeys/UID already published

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#172]
So, I understand easily how it works the first time we publish our pubkey/UID combo.

I have questions in the following cases. How should the nodes behave in the following cases (refusal, replacement... ?)

#### Case 1
 - The network has a pubkey "PBK1", the UID of this pubkey is "UID1"
 - We publish a pubkey "PBK1" with a different UID "UID2"

#### Case 2
 - The network has a pubkey "PBK1", the UID of this pubkey is "UID1"
 - We publish a pubkey "PBK2" with the uid "UID1"

**Comment by c-geek** [comment]
### Case 1
* the identity PBK1:UID1 and PBK1:UID2 coexist in the "identities sandbox", these are valid identities
* if PBK1 has been a member once, then UID2 will never be a member UID

### Case 2
* the identity PBK1:UID1 and PBK2:UID1 coexist in the "identities sandbox", these are valid identities
* if UID1 has been a member once, then PBK2 will never be a member PUBKEY

As a general rule, once a PUBKEY or UID has been a member, none of them can be affected to another member, so the associated identity will never be able to join and will stay forever in the identities sandbox.

**Comment by Insoleet** [comment]
So isn't there a risk of identities pool spam ddos ? Couldn't the nodes answer 302 to POST of UID if the uid already exists in the blockchain?

**Comment by c-geek** [comment]
Yes that would be a good behavior.

**Comment by c-geek** [comment]
Fixed in #182.
