### ISSUE TITLE
with/UD is empty

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#190]
I guess your node is overloaded and it causes crashes ?

http://metab.ucoin.io/blockchain/with/UD

**Comment by c-geek** [comment]
Same with:

* http://metab.ucoin.io/blockchain/with/tx
* http://metab.ucoin.io/blockchain/with/joiners
* http://metab.ucoin.io/blockchain/with/leavers
* http://metab.ucoin.io/blockchain/with/newcomers
* ...

**Comment by c-geek** [comment]
Fixed in 02df9fcb.
