### ISSUE TITLE
Written field is null sometimes

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#204]
Like their, cgeek certification "written" field is null : 
http://metab.ucoin.io:9201/wot/certifiers-of/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

```python3
{

    "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk",
    "uid": "cgeek",
    "isMember": true,
    "wasMember": true,
    "cert_time": 

    {
        "block": ​39669,
        "medianTime": ​1446707586
    },
    "written": null,
    "signature": "KgxRccvQ3OQ26lJx9554SdDjAq1lovmrdHFP+Xb+S9D+r1auWtcJzYwYoNrUcpBsN1E9amc4tfeunuRYElc1CA=="

},
```

Probably because you just recently issued it ! (block is 39669)

**Comment by c-geek** [comment]
Yes, it is not a bug as written in [HTTP Specifications](https://github.com/ucoin-io/ucoin/blob/master/doc/HTTP_API.md#wotcertifiers-ofsearch).

Previously this field was a Boolean, I changed it for an object that can be null.

**Comment by Insoleet** [comment]
Does it mean that certifiers of returns the same data as lookups ? Is there any difference ?

**Comment by Insoleet** [comment]
@c-geek  ?

**Comment by c-geek** [comment]
Well it is *not exactly* the same, because `certifiers-of` and `certified-by` only work with members.

So you don't see in these URIs certifications that has been made by a pubkey that is not a member (nor have been).

Lookup is wider.
