### ISSUE TITLE
Sync takes maybe too much RAM

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#206]
Sync takes almost 300/400 Mo of RAM. If it could be reduced to 100/200 Mo, it could be used on ARM board with 512 Mo RAM.

**Comment by M5oul** [comment]
At a normal running time, it takes 150 Mo of RAM. That's great!

**Comment by M5oul** [comment]
On a Digital Ocean with 512 Mio of RAM, synchronization crash because of full RAM.

**Comment by c-geek** [comment]
Ok I've made a little tweak which makes, according to `htop`, my sync process taking UP to 250 MB during sync compared to the 400 MB previously.

**Comment by Sylvain303** [comment]
could you describe the sync process, what does require such amount of RAM? (may be an new issue should be required)

**Comment by c-geek** [comment]
Remember the 2 loading bars? One for downloading, one for applying.

When blocks are downloaded, they are put into RAM. Once applied, most of them are persisted on file system, but the few hundred last will remain in in-memory DB.

Also, processing a block will add computed data (links, money sources, identities, ...) into in-memory DB.

The accumulation makes RAM being intensively used durin sync process.

**Comment by c-geek** [comment]
However we shouldn't focus too much on this issue, low RAM computers are not specifically targeted (Raspberry PI for example). Before optimizing, we need something which works. That's our first and sufficient goal.

**Comment by Sylvain303** [comment]
"low RAM computers are not specifically targeted" :  what is targeted for the RAM requirement?

When I speak about "may be an new issue should be required", it was about asking for a description of the RAM consumption, not about fixing it. No relation about this issue, nor about current targeted computer as well. Your answer is what I was looking for.

**Comment by c-geek** [comment]
There is no particular target, actually. I just want it to run on my computer first, and then try to make it work on as much devices as possible.

The very first and unique goal is: make it work on a computer. In my case, it must work on mine which is rather recent (bought 1,5 year ago).
