### ISSUE TITLE
Latest blocks containing UD are not displayed with /blockchain/with/ud

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#213]
Latest blocks containing UD are not displayed on [/blockchain/with/ud](http://metab.ucoin.io/blockchain/with/ud).

We could find blocks with UD on [blocks 40644, 40680, 40716 and 40923](http://metab.ucoin.io/blockchain/blocks/400/40608).

Issue linked to [#253](https://github.com/ucoin-io/cutecoin/issues/253).

**Comment by c-geek** [comment]
Fix with #215.
