### ISSUE TITLE
Crash at sync

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#226]
After reset data, I tried to sync on nodes, my DO and metab:
```bash
Progress:

Download: [                    ] 0 %
Apply:    [                    ] 0 %

Status: 400 - Bad request.
{}
All done.
undefined
```

**Comment by c-geek** [comment]
What is the command you ran?

**Comment by M5oul** [comment]
```bash
~/ucoin# node --harmony bin/ucoind sync --nocautious 178.62.51.52 64353
~/ucoin# node --harmony bin/ucoind sync --nocautious metab.ucoin.io 9201
```

**Comment by c-geek** [comment]
You should now be able to sync `metab.ucoin.io 45001` or `metab.ucoin.io 9201`. For your personal nodes, you will have to reset & resync them. The local DB is probably compromised.

**Comment by M5oul** [comment]
Great it works!
