### ISSUE TITLE
Add a method to retrieve identity informations

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#236]
As inso pointed in https://github.com/ucoin-io/cutecoin/issues/211#issuecomment-160055043, we do not have a straight forward way to know what is the written identity of a pubkey/uid.

Let's add a method for that: /wot/identity-of/[search]

**Comment by c-geek** [comment]
It is already possible to have it at: http://metab.ucoin.io/blockchain/memberships/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

**Comment by Insoleet** [comment]
Could you add it to the URLs : 
http://metab.ucoin.io/wot/certifiers-of/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
http://metab.ucoin.io/wot/certified-by/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
?

**Comment by c-geek** [comment]
I've done all what you wanted, but /wot/lookup. This is definitely not the place I want it to be. Maybe in another method, later!
