### ISSUE TITLE
Unify the version field

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#238]
Sometimes it's a string  : 
http://metab.ucoin.io/blockchain/Current

Sometimes it's an int : 
http://metab.ucoin.io/blockchain/memberships/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

Related issues : 
 * https://github.com/ucoin-io/ucoin-python-api/issues/12
 * https://github.com/ucoin-io/cutecoin/issues/270

**Comment by c-geek** [comment]
Oh ... here you have your full identity! http://metab.ucoin.io/blockchain/memberships/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

**Comment by Insoleet** [comment]
Ahah yes you are right, the sigDate is here ^^
