### ISSUE TITLE
Add a single entry point for install

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#241]
Instead of writing:

```
$ mkdir ucoin-v0.12
$ curl -kL https://github.com/ucoin-io/ucoin/releases/download/v0.12-beta3/ucoin.tar.gz | tar xz -C ucoin-v0.12
```

it would be better to have something like:

```
$ wget -qO- http://ucoin.io/install.sh | bash
```

that would install ucoin with last version at: `~/.ucoin`, just like [nvm](https://github.com/creationix/nvm) is doing.

**Comment by Insoleet** [comment]
Well generally it's a bad behaviour to do such things. If ucoin.io gets compromised, it could be the center of propagation of malware through this blindly executed bash file...

**Comment by c-geek** [comment]
You are right. What if we pointed directly to a github file instead? Like:

```
wget -qO- https://raw.githubusercontent.com/ucoin-io/ucoin/master/install.sh | bash
```

**Comment by Insoleet** [comment]
I guess it's OK using github. But a step by step method which extract the file is necessary too. For people with a non-standard distribution for example !

**Comment by Sylvain303** [comment]
Hi,

And why not making a debian pakage, instead?

Also debian service discussed here: http://forum.ucoin.io/t/how-to-launch-an-ucoin-node-as-a-debian-service/570

Regards,
Sylvain.

**Comment by Insoleet** [comment]
Hi Sylvain,

We would prefer not to be responsible of the packaging in the different distributions. But we welcome contributions of packagers who would like to create a package for their distribution ! (Like the one made by mildred for cutecoin for example : https://aur.archlinux.org/packages/cutecoin-git/ )

**Comment by Sylvain303** [comment]
Thanks, I will contribute that way, cloning the repos and packaging it into a .deb. Any start yet ?

**Comment by Insoleet** [comment]
You'll only have the generic installation instructions : https://github.com/ucoin-io/ucoin/wiki/Install-uCoin-node , and maybe you can inspire from what yunohost team did !

**Comment by Sylvain303** [comment]
Yep I saw this doc. who/what is yunohost team?

**Comment by Insoleet** [comment]
This question is for @M5oul :+1:

**Comment by c-geek** [comment]
@Sylvain303 I will publish detailed installation instructions today, those I use for making a complete standalone binary.

**Comment by Sylvain303** [comment]
ok, no rush. I will start a githup repos on building the .deb and find the best place to post the package. Maybe a ppa or something. I saw you, or someone else maybe, who talked about building standalone binary for ucoin, or maybe it was for a node.js application in general.

**Comment by M5oul** [comment]
@Sylvain303, [YunoHost](http://yunohost.org/) is a self-hosting distribution based on Debian. It offer services like email, XMPP chat, web server…etc. Making a one-click install. one-click app install.

**Comment by Sylvain303** [comment]
So @M5oul do you have an installer for ucoin app on YunoHost?

**Comment by Sylvain303** [comment]
I found it here: 
* https://yunohost.org/#/apps_in_progress_fr
* https://yunohost.org/#app_ucoin

Great!

**Comment by M5oul** [comment]
@Sylvain303, the update version is [here](https://moul.re/repo/moul/ucoin_ynh/).

**Comment by c-geek** [comment]
@Sylvain303 you may find bash instructions to build a binary out there: https://github.com/ucoin-io/ucoin/blob/master/install.sh#L36

**Comment by Sylvain303** [comment]
@c-geek Thanks I've seen it on your commit. Thanks.
