### ISSUE TITLE
Network: peers unavailable are still considered UP

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#245]
Consider: http://metab.ucoin.io:9201/network/peering/peers?leaves=true

See https://github.com/ucoin-io/cutecoin/issues/275

**Comment by M5oul** [comment]
Some nodes are still considered up: https://moul.re/ucoin/network/peers

**Comment by c-geek** [comment]
Fixed by 5fe3c3ba682ea0f83696d4711bd1a998430d4788.
