### ISSUE TITLE
Better way to persist the database

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#254]
Currently, LokiJS in-memory DB is persisted fully, as-is.

It would probably be interesting to split the persistence into several files, to avoid writing again and again the same data that hasn't changed.

Also, loading the database should take care of loading these bits of database and join them together.

**Comment by Sylvain303** [comment]
Also, as installer is now smooth and fast with [install.sh](https://github.com/ucoin-io/ucoin/blob/master/install.sh), we may also look at a smarter/faster database. Maybe a .deb with dependencies, or even an image, for example a docker or an VM image [turnkeylinux](https://www.turnkeylinux.org/). Or [Yunohost](https://moul.re/repo/moul/ucoin_ynh/).

Just a suggestion. Can be an improvement on LokiJS first, and a full image in another step.

**Comment by c-geek** [comment]
I close this issue for now, it is not required so early in uCoin development. I have to focus on main features.
