### ISSUE TITLE
Have www.metab.ucoin.io technical graphs working again

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#255]
http://www.metab.ucoin.io/#/blockchain/graphs no more work, since the `ucoind export-bc` is broken (way too long to execute more precisely).

**Comment by Sylvain303** [comment]
http://www.metab.ucoin.io/#/blockchain/graphs still give nothing for me.

**Comment by Sylvain303** [comment]
in fact, after a long period of download, but quite slow CPU activity, it displays some graphs…
Afterwards the firefox becomes frozen, on the main graph using one full core at 100%.

**Comment by c-geek** [comment]
Yes this code was not meant to support 45k blocs, rather hundreds or few thousands.

Maybe a better version will come out some day!
