### ISSUE TITLE
duplicate entries in /blockchain/with/certs 

### ISSUE THREAD

**Issue by Sylvain303** [ucoin-io/ucoin#257]
reproduce:

~~~
wget -O certs.json "http://ucoin2.opensource-expert.com:22022/blockchain/with/certs"
sed -n '/[0-9]/ s/,//p' certs.json | sort | uniq -c | sort -rn  | less
~~~

**Comment by c-geek** [comment]
There are only two places where stats are added to the DB:

#### [During block add](https://github.com/ucoin-io/ucoin/blob/master/app/service/BlockchainService.js#L194)

This procedure add stats for only 1 block. So this has very few probability to cause the wide range of blocks pushed to your stats (you duplicated stats for ranges of blocks).

#### [During synchronization](https://github.com/ucoin-io/ucoin/blob/master/app/service/BlockchainService.js#L1336)

This has more chances to occur. But that woud mean you had some issue with sync manipulation (maybe you called it several times?).

If you have some way to reproduce it, that would help a lot.

**Comment by Sylvain303** [comment]
Something to do, here?

Start some sync, break, restart?
ucoin doesn't continue at the current sync block it reached?

**Comment by Sylvain303** [comment]
This gives duplicate:

http://ucoin2.opensource-expert.com:22022/node/summary
~~~
{
  "ucoin": {
    "software": "ucoind",
    "version": "0.12.10",
    "forkWindowSize": 100
  }
}
~~~

reproduce:
~~~
#!/bin/bash

export UCOIN_DIR="/home/ucoin2/.ucoin"
[ -s "$UCOIN_DIR/ucoin.sh" ] && . "$UCOIN_DIR/ucoin.sh"  # This loads ucoin.sh
time ucoind stop
time ucoind reset data
time ucoind sync metab.ucoin.io 9201 --nointeractive > bug_257.log &
# CTRL-C after 5min
max=6
i=1
while [[ $i -le $max ]]
do
        sleep 10
        tail -3 bug_257.log
        i=$(($i + 1))
done
pkill -SIGINT node
tail -3 bug_257.log

echo restart syncing
time ucoind sync metab.ucoin.io 9201 --nointeractive >> bug_257.log
echo staring ucoin node
ucoind start
sleep 4 # not long enough…
wget -O certs.json "http://ucoin2.opensource-expert.com:22022/blockchain/with/certs"
sed -n '/[0-9]/ s/,//p' certs.json | sort | uniq -c | sort -rn  | less
~~~
