### ISSUE TITLE
Better sign a hash of the block than the entire block

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#268]
Currently we sign the whole block. But the bigger the block the longer the time to sign it. This is an incentive to write the smallest blocks to have a significant chance to write next block.

That's why we should rather sign a hash. This hash might be complex, have a special structure like:

```
HASH#10892-958ce5eb07b7d4a9fd804c97bd2057e59dd1867869f0186d8eeef86802a8ebb224c9fc1d7d5dd00798efa724a3d7632095539b2135f0afb171b95de3ae6bd98e
```

**Comment by Insoleet** [comment]
Actually, when you sign a block, you are already signing its hash.

**Comment by c-geek** [comment]
That's weird, because I do see the speed is slowing down as the size of the block grows.

**Comment by Insoleet** [comment]
Well, hashing gets probably slower when there are more data in the block.

Maybe we could sign just a part of the block which identify it, but would not grow when there are more data in the block ?

**Comment by c-geek** [comment]
This is exactly what I'm proposing: compute the hash of the complete data once, and sign this hash which will be very easy to sign.

However I prefer to prefix this hash with `HASH#10892-` for example to contextualize the signature.

**Comment by c-geek** [comment]
And you are probably right: the hash process might be what slows down the signature process. I hadn't any clue hashing process would have that impact :grimacing:

**Comment by Insoleet** [comment]
I'm proposing something different : sign only fields which are not expanding. Maybe transactions, certifications could be ignored in the signature of the block ?

**Comment by c-geek** [comment]
No because that would cause problems like Bitcoin transaction maleability: if you don't sign the whole content, you expose yourself to document alteration.

**Comment by Insoleet** [comment]
The time to sign is probably why bitcoin does not sign the whole block, thought...

**Comment by Insoleet** [comment]
Ok forgot what I said, it's not the reason at all.

Anyway, is it really a problem ? Because I don't see an easy fix to this problem. Since the node trying to mine many blocks by ignoring documents will see its difficulty increase really fast, I'm not even sure it's a real problem.

**Comment by c-geek** [comment]
Yes it is a problem because, if the node includes several transactions for example, the hardness to compute a proof-of-work will be higher for this node than the difficulty other nodes computing smaller blocks will have.

This is a handicap for nodes trying to add data.

Of course there is rotation because of personal difficulty, but this is limited to the portion of nodes which are excluded. The others still compete to find a new block and I think we should avoid to penalize nodes trying to add data.

**Comment by Insoleet** [comment]
I suggest one obvious fix, but maybe a bit absurd : 
We could have blocks with a size limit. When signing a block, everything after the last data must be empty until the size limit.  This way, if you don't have data,  your signature is not easier than the block with data.

**Comment by c-geek** [comment]
It's not that absurd, but why don't you agree with my initial proposal which seems really simpler to me?

**Comment by c-geek** [comment]
OK I did not get the fact I have to build my hash on each iteration (variation of the nonce) anyway, so indeed my initial idea seems wrong.

**Comment by Insoleet** [comment]
I didn't understand your initial idea this way. Now that I understand it, I think it's a pretty good idea. You could hash the data in the block except the nonce and each iteration, this hash would not change. Then signature done at each iteration would be about signing the hash of the data + the no once  instead of the block. Do I miss something here ?

**Comment by c-geek** [comment]
Yes but that was not my initial idea, what you say is what I just imagined after saying my idea was wrong.

But still we have a problem: where do we store the final hash = hash + nonce ?

We cannot store it in the block.

That's why I think your idea of blank content is the best solution we have for each node to be equal towards PoW computation!

**Comment by c-geek** [comment]
Finally I imagined how we could store the finalHash + nonce :grin: 

First, we remove the Nonce from current Block document. We now have:

```
Version: VERSION
Type: Block
Currency: CURRENCY
Number: BLOCK_NUMBER
PoWMin: NUMBER_OF_ZEROS
Time: GENERATED_ON
MedianTime: MEDIAN_DATE
UniversalDividend: DIVIDEND_AMOUNT
Issuer: ISSUER_KEY
PreviousHash: PREVIOUS_HASH
PreviousIssuer: PREVIOUS_ISSUER_KEY
Parameters: PARAMETERS
MembersCount: WOT_MEM_COUNT
Identities:
[...]
```

Then, we compute the hash I mentionned in my first message, and we would add it to at then end of the block along with a Nonce that can be changed and a signature of the hash + nonce :

```
Version: VERSION
Type: Block
Currency: CURRENCY
Number: BLOCK_NUMBER
PoWMin: NUMBER_OF_ZEROS
Time: GENERATED_ON
MedianTime: MEDIAN_DATE
UniversalDividend: DIVIDEND_AMOUNT
Issuer: ISSUER_KEY
PreviousHash: PREVIOUS_HASH
PreviousIssuer: PREVIOUS_ISSUER_KEY
Parameters: PARAMETERS
MembersCount: WOT_MEM_COUNT
Identities:
[...]
Hash: BLOCK_HASH
Nonce: NONCE
BOTTOM_SIGNATURE
```

With the following rules:

* `BLOCK_HASH` must match the hash of the content *before it*
* `NONCE` must be an integer
* `BOTTOM_SIGNATURE` must be an Ed25519 signature made on Hash + Nonce fields
* the hash of the whole document (all content, `BOTTOM_SIGNATURE` included) must match a Proof-of-Work (starting with a determined number of zeros)

This way we avoid signing blanks!

**Comment by c-geek** [comment]
So we have a solution where, indeed, we sign only a part of the block that summarize it. And all the content is still signed.

**Comment by Insoleet** [comment]
Well, it's complicating things where we could just change the basic rule  : 

Field "SIGNATURE" is a signature of the hash + noonce

**Comment by c-geek** [comment]
No it is not enough, because hash is made on the nonce.

**Comment by c-geek** [comment]
You have to put Nonce field away.

**Comment by Insoleet** [comment]
You can hash the block without the noonce, and the field "SIGNATURE" would be a signature of this hash + the noonce.

The `Hash: BLOCK_HASH` can totally be deduced from the block document, and so is not needed when you create it...

**Comment by c-geek** [comment]
Yes of course, but by adding it you can check the "block" part and the "proof-of-work" part separately. So if the PoW part (written hash + nonce + sig) fails, you do not even have to parse the block.

This is a detail, I personally prefer to write it.

**Comment by Insoleet** [comment]
Ok, I can understand, it's more explicit. Being explicit can be good most of the times :+1:
