### ISSUE TITLE
Think about a method to write exhaustive test suite for UCP

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#269]
UCP rules must be checked. If possible, we need to find a method that would allow us to have a list of tests covering all the potential cases of block.

**Comment by Sylvain303** [comment]
Could you describe your goal here, with a small example? Would it be applied externally to a ucoin's node to test if it responds correctly to the [protocol](https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md)?

Example?

~~~
test_ucp some_part_UCP http://node:port/API_locator/ expected_for_some_part_UCP
~~~

**Comment by c-geek** [comment]
The goal here is to have unit tests of in-memory core code, withtout any binding to external HTTP connection neither any plugged-in database.

Tests that would allow us to check surgically each single rule of the protocol, with many different configurations, all written by hand so we can also test easily marginal cases.

However, your idea of a higher level testing with the node being in a target environment (file database, http contact) would also be nice. About it, I think we should make 3 types of tests:

* single node being tested against a pre-defined scenario
* multiple nodes  being tested against a pre-defined scenario (to test forwarding & synchronization for example)
* multiple nodes stress test (to have scaling measurements)
* CLI tests

**Comment by c-geek** [comment]
After some coding, we how have a better framework for testing:

* we have a central folder at [/test/fast/block](https://github.com/ucoin-io/ucoin/tree/master/test/fast/block) where the 3 levels of rules are described:
    * format
    * local
    * global

These are **unit** tests, without preset environnement. So no database plugged in, no HTTP, nothing. Just pure code.

While *format* and *local* tests are stateless code, *gobal* requires to retrieve data for its tests. The workaround is to mock the data access methods, just like in this code testing `checkKickedMembersAreExcluded` rule and which requires `getToBeKicked()` data access method:

```js
it('a block with kicked members not well written under Excluded field should fail', test(rules.GLOBAL.checkKickedMembersAreExcluded, blocks.KICKED_EXCLUDED, {
  getToBeKicked: () => Q([
    { pubkey: 'HgTTJLAQ5sqfknMq7yLPZbehtuLSsKj9CxWN7k8QvYJd' },
    { pubkey: 'G2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU' },
    { pubkey: 'D2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU' }
  ])
}, function (err) {
  should.exist(err);
  err.message.should.equal('All kicked members must be present under Excluded members');
}));
```

If we want to go deeper later on, we should also have unit tests for data access layer and CLI as well.
