### ISSUE TITLE
builder script for ucoin binary install

### ISSUE THREAD

**Issue by Sylvain303** [ucoin-io/ucoin#272]
[install.sh](https://github.com/ucoin-io/ucoin/blob/master/install.sh) is using a binary built node.js libs for fast install. Could you publish the builder scripts so we could also build ARM images for raspberry nodes.

**Comment by c-geek** [comment]
Binary build is done with `install_ucoin_from_git`: https://github.com/ucoin-io/ucoin/blob/master/install.sh#L66

It is divided in 3 parts:

1. [Fetch sources](https://github.com/ucoin-io/ucoin/blob/master/install.sh#L103-L155)
2. [Download Node.js & NPM binaries](https://github.com/ucoin-io/ucoin/blob/master/install.sh#L157-L182)
3. [Build uCoin](https://github.com/ucoin-io/ucoin/blob/master/install.sh#L184-L187)

**Comment by Sylvain303** [comment]
Ah, OK. Right. 
I missed the point n°3. 
The node.js detection is obviously broken on arm architecture, at n°2.

~~~
=> Downloading 'http://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x86.tar.gz' to '/home/ucoin2/.ucoin/node.tar.gz'
~~~

I will modify install.sh to take care of it if possible, and see, if I can reproduce the fast install.

Thanks.

**Comment by Sylvain303** [comment]
Some arm prebuild version of node.js exists, but not for version 0.12.7. What is the limitation of this specific version of node.js and ucoin?

**Comment by c-geek** [comment]
This version allow us to write JavaScript ES6 code, which is way easier to read and maintain.

As I see, only 0.10.x versions of Node.js are available on ARM. I am right?

**Comment by Insoleet** [comment]
On ARM maybe we should use the following repo :  https://github.com/nathanjohnson320/node_arm

**Comment by c-geek** [comment]
@Insoleet your previous links was good also! https://github.com/nathanjohnson320/node_arm#installing-node-for-arm-tested-on-raspberry-pi-model-b

0.12.6 Node.js version is OK.

Because with NVM we will be limited to 0.10.x, since it simply walks through http://nodejs.org/dist/ and no ARM version exists out there.

**Comment by c-geek** [comment]
So I should definitely not do #166 to run uCoin with Node v4!

**Comment by Insoleet** [comment]
So how will the install.sh work on raspberry pi ?

**Comment by Sylvain303** [comment]
It partially works. ucoind shell wrapper based on local nodejs, is failing. But the [yunohost install script](https://moul.re/repo/moul/ucoin_ynh/src/master/scripts/install) does install nodejs 0.12.9 which seems to work.

I started the node that way:

~~~
ucoin@raspberrypi:~ $ cat start.sh 
cd ~/ucoin/
nohup node --harmony ~/ucoin/bin/ucoind start >> ~/ucoin.log &
~~~

yunohost uses: https://deb.nodesource.com/setup_0.12 

Which is a script which uses debian packaging system, which is not used by [install.sh](https://github.com/ucoin-io/ucoin/blob/master/install.sh)

I will go deeper in the install process and let you informed.

There's nodejs ARM prebuilt for nodejs 4.x and above.

Compiling nodejs 0.12.7 on raspberry PI, took 92min. And distributing precompiled image of nodejs may require to sign the build. 

I personally think that everything shipped precompiled must be signed, at least when we'll reach version 1.0. As a money network, everything must be based on confidence, and must be verified.

**Comment by c-geek** [comment]
@Sylvain303 that's great news! So I can try to use node@4.x :smiley: 

Agreed about binary signature.

**Comment by Sylvain303** [comment]
debian package are signed…

**Comment by c-geek** [comment]
So if you make a uCoin .deb package, we will be able to sign it. I dunno however what the signing process consists in, who owns the key (PGP key?), etc.

Do you know all of this?

**Comment by Sylvain303** [comment]
yes .deb signing mechanism uses the PGP key provided by the builder. And much more. I believe that .deb is the most complete and robust packaging system.

In a second time I will investigate on building a .deb for ucoin. #276

For this issue, I think your first answer is sufficient, and we can now close. I now know how to build the binaries.

The install.sh + ucoind.sh wrapper are based on the availability of nodejs 0.12.7 locally, which is perfectly ok if all binaries are available somewhere… Which works for x64 very well thanks. 

For ARM that an other issue… We could also distribute an sdcard image with a raspbian-jessie dedicated for ucoin, but I find it more useful to base it on [yunohost](yunohost.org) as suggested first.

**Comment by c-geek** [comment]
Great, I let you choose the best solutions.

AFAIC, I will have a look at #166 and try to target Node v4 as JS engine.

**Comment by c-geek** [comment]
I am currently testing: crypto libs ([scrypt](https://github.com/barrysteyn/node-scrypt), [naclb](https://github.com/c-geek/naclb)) seems to be compliant with Node v4. naclb required some code upgrade, but it's working fine.

So I will target Node v4.

**Comment by Sylvain303** [comment]
It seems a fair option to target a newer version. It will also gives a nice overview of an active and uptodate project. It should not stop me to use actual material to build something at early stage. ;)

Thanks for your work.

**Comment by Sylvain303** [comment]
Do you have a script that build up the .tar.gz binary available here?

https://github.com/ucoin-io/ucoin/releases
for example => https://github.com/ucoin-io/ucoin/releases/download/v0.12.10/ucoin-x64.tar.gz

nodejs is shipped inside.

According to this [documentation about release](https://help.github.com/articles/creating-releases/) it's not automatic.

It seems to comes from travis? (I don't know this build plateform yet)

According to this [doc](https://help.github.com/articles/creating-releases/) it is scriptable.

**Comment by c-geek** [comment]
Yep, right here: https://github.com/ucoin-io/ucoin/blob/master/.travis.yml

**Comment by Sylvain303** [comment]
Hey, this one is great! That's what I was looking for:

~~~yaml
before_deploy:
  # Download & embed Nodejs binary
  - NVER=`node -v`
  - wget http://nodejs.org/dist/${NVER}/node-${NVER}-linux-x64.tar.gz
  - tar xzf node-${NVER}-linux-x64.tar.gz
  - mv node-${NVER}-linux-x64 node
  - rm node-${NVER}-linux-x64.tar.gz
  # Clean testing packages
  - npm prune --production
  - tar czf ../ucoin-x64.tar.gz ./ --exclude ".git" --exclude "coverage" --exclude "test"  --exclude "share"
~~~
