### ISSUE TITLE
make a debian package .deb for distribution

### ISSUE THREAD

**Issue by Sylvain303** [ucoin-io/ucoin#276]
Replace or complete install.sh installation mechanism by a debian package.

* Document the building of the package.
* List dependencies.
* May be blocked by #166

**Comment by Sylvain303** [comment]
I propose that the debian package building should be progressive.

It's a good idea to first keep using nodejs internally in the package. I mean having a specific
version of nodejs installed with ucoin. So nodejs compatibility will be handled in the package.

For maintaining the package building I propose some options, to be discussed here in French first:

https://annuel.framapad.org/p/ucoin_debian_package_building

**Comment by Sylvain303** [comment]
OK. I sum-up the reflexion:

I started a depot which will holds the package source separately:

https://github.com/Sylvain303/ucoin-debian-package 

The idea is to process by step. I'll first build a working debian package .deb, which will be look like to what is done by [install.sh](https://github.com/ucoin-io/ucoin/blob/master/install.sh)

* installing a local version of nodejs
* installing ucoin
* compiling local architecture dependent code. (amd64 and armv7)

This will necessary includes some alteration to install.sh and ucoind.sh wrapper. Which is handled by debian's packaging tool-set.

A more debian compliant package will be build next.

So lets this ticket open, I will post update in it.
If issues happen on the package post on the dedicated repository => https://github.com/Sylvain303/ucoin-debian-package/issues

**Comment by Sylvain303** [comment]
Happy new year guys.

I drafted some changes in [install.sh](https://github.com/Sylvain303/ucoin/blob/sylvain/install.sh#L157) and added a dummy [Makefile](https://github.com/Sylvain303/ucoin/blob/sylvain/Makefile).

The modifications in install.sh is for code reuse, and to be DRY (Dont Repeat Yourself), I splited 
`install_node_js()` from `install_ucoin_from_git()` and added a command line switch `--call-only` for the script.

I use it in the draft Makefile:

~~~Makefile
node/bin/node:
	${INSTALL_UCOIN} --call-only install_node_js ${NODEJS_VER} .
~~~

Which purpose is to load the original script but only execute the newly available `install_node_js()` function, with the 2 arguments.

So my questions are related to the way  you'd like to work with the debian package building script:

* Do I pull-request the inclusion of install.sh for your own usage too?
* Or, Should I split install.sh into common reusable shell helper functions?
* Do you want I also pull-request the Makefile? It means I will probably merge some behavior of install.sh into Makefile rules, to be DRY compliant, and also because it's really a Makefile jobs…

may be `pipe install.sh | bash` would become:

~~~
git clone ucoin
make install-local-user
~~~

Or some mixed solution…

Tell me, as I can also maintains debian.patches on the packet side which will be applied by debhelpers when the package is build.

I'll push a working version on the https://github.com/Sylvain303/ucoin-debian-package as soon as I've the first build that works…

Sylvain.

**Comment by Sylvain303** [comment]
News from the .deb: It can now build partially with debian tools, the Makefile is created by the package source itself, could be accomplished some other way. The result of the build is: 

* nodejs downloaded and extracted
* npm install has built all the libs

now it needs to be installed somewhere. I proposed to first use `/home/ucoin/.ucoin` similarly to what is done by `install.sh`. Needs to be changed in the future to fit with debian's policy.

I'm reading more deeply `install.sh` and its tight link to `ucoin.sh` which proposes a shell function which is the shell wrapper to nodejs bin/ucoind (javascript)

I'm going to rewrite what I need to both script by strictly keeping existing behavior. I mean, I'm gonna change both ucoin.sh and the ucoind function and install.sh to be usable by my installer, but still providing the same call syntax.

You will see the result in the pull-request.

**Comment by c-geek** [comment]
It is OK if you change ucoind.sh and install.sh files by keeping the exact same syntax + exact same behavior. You can also include the Makefile with the same condition.

Will you push soon to your github repo so I can have a preview of these files?

**Comment by Sylvain303** [comment]
Modified `install.sh` and `Makefile` are available here, but not yet achieving the goals mentioned above.

https://github.com/Sylvain303/ucoin/blob/sylvain/Makefile

It is not at all portable yet, assuming my ucoin clone to be in $HOME/ucoin.

I faced binary lib dependencies complain by the debhelper dh_shlibdeps, which is probably because of the build is done by a local nodejs version and not by a debian's one. I stopped to progress here and the installer didn't go forward.

I'm also still in progress to provide script helpers, but I started to use a released tarball and I should now move to a git helper: like described [here](https://www.debian.org/doc/manuals/maint-guide/build.en.html#git-buildpackage)

I didn't push package draft because it's mostly broken and don't live well in nodejs multiple version environment…

**Comment by c-geek** [comment]
I have to admit I do not understand at all the Makefile :smile: 

However about ucoin.sh & install.sh, it seems OK.

**Comment by c-geek** [comment]
Quite a long time since this comment, now we have .deb packaging for [all our new releases](https://github.com/ucoin-io/ucoin/releases) of Duniter (the new name to come for uCoin).

The install.sh script will be used for compilation install of the server instead, from now on. It already works for Debian 6 installation.

I don't know if you still want to work on this script, so I close the issue. Feel free to reopen it.
