### ISSUE TITLE
describe memory usage

### ISSUE THREAD

**Issue by Sylvain303** [ucoin-io/ucoin#284]
following #206 

Make a documentation about how ucoin is using memory RAM and disk at different stage.
* sync
* reset
* normal running ucoin's node

**Comment by c-geek** [comment]
I put it as "Horizon" milestone because this is absolutely no priority task, since DB layer is still very subject to changes.

I will probably go back to [LevelDB](https://github.com/google/leveldb) storage soon with most data, which will drastically reduce memory consumption.

**Comment by Sylvain303** [comment]
@M5oul, much more a documentation task than a "question". In the mind I'm asking about. ;) I'm focusing on #276, I may look at it myself after. But it can take quite a lot of time, in fact.

**Comment by c-geek** [comment]
Since commit 920e00862d622b1db6281ae45deeebed0856fe35 I now use SQLite instead of in-memory LokiJS DB.

So there is not particular memory usage to document, uCoin is just a controller between the Internet and its local DB.
