### ISSUE TITLE
Wot behavior

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#291]
I have nine certifications whose three which will expire the 7th, 9th and 9th January. Sakia tells me my certification will expire soon. I think one time this three certifications will expire I will no longer be a member.

As kimamila and sb needed to renew their membership even if their had enough certifications.

Is this behavior desired?
I think it would be better to automatically switch from dying to new certifications without having to renew membership.

**Comment by c-geek** [comment]
It is not particularly desired, it is just a consequence of the rules.

However this problem is "annoying" because we have very quick expiration of certifications so the renewal process often occurs.

**Comment by M5oul** [comment]
Ok.
