### ISSUE TITLE
Issue on blockchain/blocks/[count][from]

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#292]
Issue on [blockchain/blocks/[count][from]](https://github.com/ucoin-io/ucoin/blob/master/doc/HTTP_API.md#blockchainblockscountfrom)
works for http://scith.ovh:8999/blockchain/blocks/100/46000
but not for http://scith.ovh:8999/blockchain/blocks/200/46000
I could do big asks http://scith.ovh:8999/blockchain/blocks/2000/44000
Current block is 46691.

**Comment by c-geek** [comment]
With was probably a bug of the DAL. I switched to a less complicated layer with SQLite. The bug should be fixed now.
