### ISSUE TITLE
Remove PM2

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#296]
PM2 was a good start to handle uCoin as a daemon, but now it becomes a mess just to rotate logs.

**Comment by M5oul** [comment]
What do you mean about logs? pm2 is a mess to manage logs?

**Comment by c-geek** [comment]
Yes, in the case of uCoin it is a mess. Otherwise PM2 is a good tool!

Because in our case, PM2 has a module called pm2-logrotate, but an installation locally (as I bundle uCoin in a tarball and do not want users have to download/install anything else than this tarball) is buggy, it just throws exception on install.

I could handle logs through uCoin in such a way PM2 wouldn't have to be the logger, instead uCoin could directly write its logs with rotate features (using [Winston](https://github.com/winstonjs/winston) logger for example). But still, PM2 will write logs (few, but it will). And PM2 does not seem to allow logs to be disabled.

So I just end removing it. Also, I've found [daemonize2](https://github.com/niegowski/node-daemonize2) which is great for low level daemon management, and that's really cool :+1:

**Comment by M5oul** [comment]
Ok.
