### ISSUE TITLE
While Sync'ing : processus killed or pipe broken

### ISSUE THREAD

**Issue by sbDevGit** [ucoin-io/ucoin#298]
Hi ;)
I saw some already opened issues about sync errors, I don't know which one I have to choose
Well, I create a new one

I got 5 stopped processus while syncing
my command `ucoind sync metab.ucoin.io 9201`
the error :
https://ipfs.pics/ipfs/QmRW3UpBvTNVBqfXB7H7nTpXspuaNoEXnSodYYtEbsnXf5
It seems to bug at "4 minutes left"
It makes one time until "1 min left" 88%~

**Comment by M5oul** [comment]
I think this won't happen with uCoin 0.13.

**Comment by sbDevGit** [comment]
more info : I have the version 0.12.10

**Comment by c-geek** [comment]
Ok I consider this bug won't reproduce with 0.13+. Please reopen if it happens again, or you may create another issue if you prefer.
