### ISSUE TITLE
Websockets ?

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#309]
Hello,

Are the websockets working correctly ?

I tried multiple clients, I can't find a way to use them : 
With [tyrus](https://blogs.oracle.com/PavelBucek/entry/websocket_command_line_client) : 
```
➜  ~  java -jar tyrus-client-cli-1.1.jar http://metab.ucoin.io:9201/websocket/block
# Connecting to http://metab.ucoin.io:9201/websocket/block...
# Failed to connect to http://metab.ucoin.io:9201/websocket/block due to Incorrect scheme in WebSocket endpoint URI=http://metab.ucoin.io:9201/websocket/block
tyrus-client> 
```

With [chrome client](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo) , i get error 'undefined'.

And with `aiohttp`, I get errors too.

Any idea ?

**Comment by Insoleet** [comment]
I feel like socket.io may be a bit too high level for BMA, and that basic websockets would be better - https://davidwalsh.name/websocket

What do you think ?

**Comment by c-geek** [comment]
I will have a look at it this afternoon, I will include it for version 0.14.

**Comment by Insoleet** [comment]
Could you specify in the API what exactly do we receive on the websocket ? Raw blocks ? Json data ?

**Comment by c-geek** [comment]
Answer is JSON string:

* for /block you receive a JSON block
* for /peer you receive a JSON peer

**Comment by c-geek** [comment]
Note: I've not sanitized the objects yet, so they might differ a bit from what is expected (`raw` field missing, extra fields like `fork`, ...).
