### ISSUE TITLE
Memberships documents and the blockchain

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#313]
In the following URL : 
http://metab.ucoin.io/blockchain/memberships/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

We cannot find the original membership document in the blockchain : 
http://metab.ucoin.io/blockchain/Block/34526

There is probably something I'm missing here ?

**Comment by c-geek** [comment]
The block numner here is just a timestamp. The membership is probably written some blocks later.

**Comment by Insoleet** [comment]
Ok, it would be great to be able to make the link between this url and the blockchain, since it's a blockchain/ url !

**Comment by c-geek** [comment]
I will add a `written: 48702` field to indicate the block in which the membership was written.

Will be a number or `null` if the membership was not written.
