### ISSUE TITLE
Logs display issue

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#323]
After reinstalling uCoin node `git pull && npm install` or after a Node.js update, `ucoind logs` commands display logs from the beggining. It also happend me one time that it display the whole logs in a loop :smile:

**Comment by M5oul** [comment]
It's strange, it display the path of the log file:
```sh
ucoind logs
/root/.config/ucoin/ucoin_default/ucoin.log
```

**Comment by c-geek** [comment]
You have to reopen your terminal.

**Comment by M5oul** [comment]
Ok, thanks.
