### ISSUE TITLE
Memberships url returns null field in written

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#331]
An example : 

http://twiced.fr:15296/blockchain/memberships/HBSSmqZjT4UQKsCntTSmZbu7iRP14HYtifLE6mW1PsBD

```json

{

    "pubkey": "HBSSmqZjT4UQKsCntTSmZbu7iRP14HYtifLE6mW1PsBD",
    "uid": "Pirion",
    "sigDate": ​1451772411,
    "memberships": 

[

{

    "version": ​1,
    "currency": "meta_brouzouf",
    "membership": "IN",
    "blockNumber": ​48697,
    "blockHash": "0000085110CF982054BAF8F56D23CEA21F9F4F1C",
    "written": null

},
...
```

**Comment by c-geek** [comment]
Yes, is this anormal? It means the membership has not been written yet.

If you look at http://twiced.fr:15296/blockchain/memberships/inso for example, you won't have `written: null`until you click in Sakia on "Renew membership" which will add a non-written membership in the *to-be-written* pipe.

**Comment by Insoleet** [comment]
It's normal, I fixed it since then !
