### ISSUE TITLE
[Feature Request] Allow Certifications to be Revoked

### ISSUE THREAD

**Issue by Idyllei** [ucoin-io/ucoin#332]
There has been discussion of setting a limit to how many certifications a member of a community can publish. I do not know if this has been implemented as of yet. 

However, if it __is__ implemented, it could be catastrophic to @c-geek 's [Proposal to Change the Distance Rule](https://forum.ucoin.io/t/proposition-for-changing-the-distance-rule/668). 

I say this because, in order for the proposal to work, one must certify many others once they are a member of a community in order to keep the community healthy. If we limit how many certification a person may publish, we are limiting the proximity of any one node to every other node. 

By allowing a member to revoke a certification, we save him from having to wait for the certification to expire before being allowed to release a new certification (if his allotted certification stock has been filled).

Another benefit of allowing certifications to be revoked is that members of a community can *quickly respond to any malignant members* of their community. That has the potential to greatly increase the security and speed of threat-diversion in the community.

**Comment by c-geek** [comment]
Thanks for your proposal, however I won't implement cert revocation for [these reasons](https://forum.ucoin.io/t/certification-best-practices/617/23).

Also, if your concern is about being able to have a *sufficient* stock to not be stopped in certification process, well it depends on the stock size and the individual: for my humble individuality 50 cert stock is way enough, for others 130 won't be, so this is yet another relative limit.

For our very first experiment, we will use some value around 50 cert stock. If this value seems too low, the protocol could evolve to allow higher values anyway.

Hope this convince you :wink:
