### ISSUE TITLE
After a delay without renewal, strongly revoke identity

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#336]
An identity which has not been renewed after some time should be definitively banned, so it cannot join again.

This is needed in cases of lost of identity's keys: because withtout the keys, it is impossible to strongly revoke the identity and we cannot prove to others our good will to not create a Sybil account.

But with this mechanism, even if we lost the keys the identity can be banned after some times which will be a suficient proof that we won't have a Sybil account.

**Comment by c-geek** [comment]
Implication: we cannot revoke explicitely (identity revocation document) an identity which is already revoked by delay.

**Comment by c-geek** [comment]
See https://forum.ucoin.io/t/protocol-implicit-revocation/689/11

**Comment by vtexier** [comment]
I suggest that the delay between excluded -> revoked should be the duration of a membership renewal, not twice.

renewal -> 1 year -> excluded -> 1 year -> revoked.

**Comment by c-geek** [comment]
Yes that's what I meant and what is implemented.
