### ISSUE TITLE
Do not accept too old identities

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#339]
Identities are timestamped with a blocktime.

It would be interesting to avoid old identities to be included in the blockchain, so for example an identity which never joins won't have to keep its revocation certificate forever to avoid the identity being used by someone.

**Comment by c-geek** [comment]
Ok, for the sake of simplicity, we won't add this rule. We will rely on users to avoid signing old identities.

**Comment by Insoleet** [comment]
I think the old identities documents should be dropped from the pool sometime.

**Comment by c-geek** [comment]
Yes it will, but it does not avoid someone to create an identity signed in the past, which was the initial goal of this rule.
