### ISSUE TITLE
Why no block UID in INPUTS ?

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#347]
I'm reading the new specification behind UCP 0.2, and I was wondering why dividends inputs uses the Block_id instead of the Block_uid. What happens if the blockchain forks ?

**Comment by c-geek** [comment]
It uses `BLOCK_ID` (a number) because there is absolutely no ambiguity about the block referenced by a given numer: it exists only 1 block for each number.

About forks: what is your trouble? A fork is a valid blockchain, so a transaction written in block#100 of fork A refering to UD of block#80 and respecting the rules about amounts is OK.

**Comment by Insoleet** [comment]
Well, what if a block 80 has a dividend of 10 and another fork has 12, and one individual is a member in a fork but not in the other ? How do you validate the transaction?

**Comment by c-geek** [comment]
Then output sum won't equal input sum, the transaction will be refused.

**Comment by c-geek** [comment]
Also, if input sum was equal to output sum, the transaction would have been valid in both branches.

**Comment by Insoleet** [comment]
So I guess nodes will apply transaction in every fork they know ? Or only the current branch they are working on ?

**Comment by c-geek** [comment]
Any transaction is always tested against a given blockchain. When you have a fork, you have 2 blockchains.

So if you talk about a user that sends a transaction now, and you wonder how the node will react given the fact it has 2 blockchains (1 fork), the answer is: the node will test it against its main blockchain among available blockchains. If the user take 120 from UD which value is 80 in main blockchain, the transaction is refused.

But if you talk about a transaction being in a block, then the transaction is tested *against the block's blockchain*. If the block belongs to a fork, the transaction will be tested against the fork.

**Comment by Insoleet** [comment]
Ok, I get it. I think it makes sense, since on the client we use sources available from a given blockchain, only nodes on this blockchain should be receiving the broadcasted transaction. You can close this issue !

**Comment by c-geek** [comment]
Yes only them, you got it indeed. Closed! :-)
