### ISSUE TITLE
Consistency of inline memberships

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#350]
Just wondering if the inline memberships : 

```
PUBLIC_KEY:SIGNATURE:NUMBER:HASH:I_BLOCK_UID:USER_ID
```

Couldn't be written as : 

```
PUBLIC_KEY:SIGNATURE:NUMBER-HASH:I_BLOCK_UID:USER_ID
```
or 

```
PUBLIC_KEY:SIGNATURE:BLOCK_UID:I_BLOCK_UID:USER_ID
```

**Comment by c-geek** [comment]
Yes you are right, I will use the one with `BLOCK_UID`. I should even call it `M_BLOCK_UID` to tell it is the membership timestamp, and also use this notation in membership document.
