### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by cdadou** [ucoin-io/ucoin#368]
the software stops after setting the currency on windows 10

**Comment by M5oul** [comment]
Do you have error logs?

**Comment by cdadou** [comment]
Sorry i don't have log error, juste blackscreen

Le 24/03/2016 18:11, M5oul a écrit :
>
> Do you have error logs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/ucoin-io/ucoin/issues/368#issuecomment-200931688>
>

-- 
Chrétien Damien

2 rue Louison Bobet
53100 MAYENNE

cdadou72@hotmail.com

**Comment by c-geek** [comment]
I've met the issue too, but after a retry it worked. Could you do it?

**Comment by cdadou** [comment]
désolé je viens de réessayer l'ecran est toujours noir, après le lancement (give a try)

**Comment by c-geek** [comment]
Issue moved to [ucoin-io/ucoin-ui #9](https://github.com/ucoin-io/ucoin-ui/issues/9) via [**ZenHub.io**](https://www.zenhub.io/)
