### ISSUE TITLE
Certification to same identity was accepted in block 0

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#369]
I was able to send a certification to myself on block 0.

**Comment by c-geek** [comment]
Were you able to commit this block? The code tells me no.

**Comment by Insoleet** [comment]
I don't think so since clicking on "Accept this block and start currency" was stuck. But no error was displayed.

**Comment by c-geek** [comment]
I was wrong, it was possible even to commit the block. Now none is possible :-)
