### ISSUE TITLE
Cancel and go to home page does not reset currency

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#370]
I instanciated a currency called "TestNet" and configured it. I wanted to reconfigure it from the starts because I corrupted the block 0. So I clicked on cancel, went to home page. I configured the currency again with the same name, I clicked on "Try to gen block", and I found the same block as previous currency.

**Comment by c-geek** [comment]
Issue moved to [ucoin-io/ucoin-ui #8](https://github.com/ucoin-io/ucoin-ui/issues/8) via [**ZenHub.io**](https://www.zenhub.io/)
