### ISSUE TITLE
HTTP API > wot/lookup   meta.timestamp = blockUid ?

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/ucoin#378]
A lookup like this one : http://twiced.fr:9330/wot/lookup/cgeek

will return:

> {
>     "partial": false,
>     "results": 
>          [
>           {
>     "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk",
>     "uids": [
>   {
>     "uid": "cgeek",
>     "meta": 
>                     {
>                         "timestamp": "0-E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"
>                     },
>                     "revoked": false,
>                     "revocation_sig": null,
>                     "self": "8muE9u43Y10ua2+CQPtksjxM6vKqQijbFP+8KVRR/hbBBvCwKFXEMN2EX5IlFmWbZOE9XU1ezVhTLmII7sQkAA==",
>                     "others": [ ]
>                 }
>             ],
>             "signed": [ ]
>         }
>     ]
> }

Why not to rename meta.timestamp into blockUid ?

**Comment by c-geek** [comment]
Because it is a timestamp (a stamp of time). The fact its form is a block_uid is secondary.
