### ISSUE TITLE
tx/sources : need unlock condition 

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/ucoin#380]
Why not to give the unlock condition, in the HTTP API tx/sources ?

**Comment by Insoleet** [comment]
I think we agreed with cgeek to only display available transactions in this URL.

**Comment by c-geek** [comment]
Yes I remember: this URI only returns the sources with the simple `SIG(uri_pubkey)` condition, so the sources that the `puri_pubkey` can spend with just its signature.
