### ISSUE TITLE
Confirmations

### ISSUE THREAD

**Issue by galuel** [ucoin-io/ucoin#50]
Confirmation should be made for those different acts : 

- Time lap confirmation after asking to leave the community (you ask to leave, people connected to you have the information, time after it aks you to confirm, can be at the end of time lap signature validity).

- Confirmation to receive a transaction. Right now one can send a transaction to another member, but the receiver doesn't confirm if he is ok or not to receive it. As a transaction is a P2P exchange, it might be asking P2P confirmation, one for sender when creating the transaction, and one to the receiver. You can have a minimum a maximum time lap between sending, and then confirming the transaction by receiver.

**Comment by c-geek** [comment]
1. Yes, we've already talked about it. It will be done.

2. With current protocol, we have the possibility to do *both*: either an atomic transaction (a cheque), either a handshake.
