### ISSUE TITLE
/tx/process (compact format) > Server error "Version unknown"

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/ucoin#56]
I send this TX document :
TX:1:1:2:1:1
  G2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU
  0:T:2193:8A3FCE677803797543B5D20FF4B336792E054601:1
  0:T:2201:AD1AA67D02BE53F65E4D1E6D5B5439A301D3EA38:399
  5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of:400
  my comments1422994650516
    Q0rgFYHQRyVynAfOY6zteYybiB83Z5VU244FX0R5sxfT8eQr5m9aX9ZDiPPu9PsIo8CLxXaeSEW+GwKxGar5AQ==

But my node refused it with message on log : "[WARN] http - Version unknown"

What is my mistake ?

**Comment by c-geek** [comment]
You are trying to send the *block representation* of a transaction, whereas what is expected is *common representation*.

In your case, what is expected is:

	Version: 1
	Type: Transaction
	Currency: beta_brousouf
	Issuers:
	G2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU
	Inputs:
	0:T:2193:8A3FCE677803797543B5D20FF4B336792E054601:1
	0:T:2201:AD1AA67D02BE53F65E4D1E6D5B5439A301D3EA38:399
	Outputs:
	5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of:400
	Comment: my comments1422994650516
	Q0rgFYHQRyVynAfOY6zteYybiB83Z5VU244FX0R5sxfT8eQr5m9aX9ZDiPPu9PsIo8CLxXaeSEW+GwKxGar5AQ==

**Comment by blavenie** [comment]
ok, so what is the usage of a compact representation, in ucoin ?
Is it interresting to use it somewhere ? (e.g. in a phone app, to reduce network volume ?)

**Comment by c-geek** [comment]
It is only for blocks. So unless your app generates and/or reads blocks, you don't really care about compact format.
