### ISSUE TITLE
Alert when new version

### ISSUE THREAD

**Issue by galuel** [ucoin-io/ucoin#57]
I suggest the feature that uCoin alert the user when a new version is available, and where to go to have instructions to download / install it.

**Comment by M5oul** [comment]
Same as [here](https://github.com/ucoin-io/cutecoin/issues/46). One time uCoin will be package for distributions, the distribution package manager will manage the update easily. uCoin will mainly works on free-OS, so we don't really need that feature.

**Comment by c-geek** [comment]
@M5oul is right to me, this is not core code issue, but packaging.
