### ISSUE TITLE
Unable to install on 32 bits Ubuntu distribution

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#59]
Logs is:

	gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.25"
	gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/naclb/.node-gyp"
	make: entrant dans le répertoire « /usr/lib/node_modules/ucoin/node_modules/naclb/build »

...

	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
	gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
	gyp ERR! System Linux 3.13.0-43-generic
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/scrypt
	gyp ERR! node -v v0.10.25
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok 

...

	npm ERR! Linux 3.13.0-43-generic
	npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ucoin"
	npm ERR! node v0.10.25
	npm ERR! npm  v2.1.14
	npm ERR! code ELIFECYCLE

	npm ERR! scrypt@3.0.1 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the scrypt@3.0.1 install script 'node-gyp rebuild'.
	npm ERR! This is most likely a problem with the scrypt package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls scrypt
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/olivier/npm-debug.log

**Comment by M5oul** [comment]
Same issue on Ubuntu 15.04 on a [DigitalOcean](http://digitalocean.com/).
Same as https://github.com/ucoin-io/ucoin/issues/75 and https://github.com/ucoin-io/ucoin/issues/93.

**Comment by M5oul** [comment]
Works on Ubuntu 15.04 / 32 bits with uCoin 0.11.11 and node 0.11 :)

**Comment by c-geek** [comment]
Seems to be fixed since 5b52258.
