### ISSUE TITLE
OpenBazaar support

### ISSUE THREAD

**Issue by HLFH** [ucoin-io/ucoin#63]
Hi,

Please support the decentralized marketplace OpenBazaar: https://github.com/OpenBazaar/OpenBazaar

It's far better to pay with a uCoin-based currency than a BitCoin-based currency.

Thanks in advance,

**Comment by c-geek** [comment]
Not sure of what feature uCoin needs to be usable with OpenBazaar.

**Comment by c-geek** [comment]
Since uCoin will be able to handle things like cross-chain transactions ( #68 ), it should be compliant with OpenBazaar out of the box.
