### ISSUE TITLE
tx/history : missing transactions

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/ucoin#69]
I found some operations are missing, in the /tx/history/[pubkey]  function.

Example : 
 1. gab (FvyUNZYDjcAcH1dwvGNYoJf5C7A81NAZVESX5toNzwx6) send 100 000 units to eis (D3DGfBJdKvc7EVoyAoGLw4ax7wdpAEefXHrvsCjcwnTC)
 2. this transaction has been written into block #14557 (tx fingerprint: 676324B3F2615FD347672958C1956B81FCBD30B6)
 3. the history does not whow this transaction :
   - for gab history : http://metab.ucoin.io:9201/tx/history/FvyUNZYDjcAcH1dwvGNYoJf5C7A81NAZVESX5toNzwx6/blocks/14557/14557
   - for eis history : http://metab.ucoin.io:9201/tx/history/D3DGfBJdKvc7EVoyAoGLw4ax7wdpAEefXHrvsCjcwnTC/blocks/14557/14557

**Comment by c-geek** [comment]
It seems the issue is no longer observable. If you it again, please let me know.

**Comment by blavenie** [comment]
cool ! Thks
