### ISSUE TITLE
Add push mechanism to inform about blockchain state

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#73]
Currently, client softwares like Cutecoin have to regularly *pull* current state of a node's blockchain (to know last added block).

This is kind of inefficient mechanism. uCoin could probably provide a push mechanism for example using websocket for its BMA API.

**Comment by blavenie** [comment]
Sounds good !

**Comment by c-geek** [comment]
Would be good to push both:

* block data (new block added)
* peer data (new peer discovered/updated)

**Comment by c-geek** [comment]
Done in 73ca26aa0b79a94b15a3f49f4bffc8a9db2f486a.
