### ISSUE TITLE
wizard does nothing and it never asks for manual config

### ISSUE THREAD

**Issue by JBitD** [ucoin-io/ucoin#98]
This behavior seems to be a consequence of #78 being fixed this morning. Now after I init ... it asked once if I wanted to manual config, but I chose the wrong option, because it went straight to those blue progress bars, and every time I init it immediately syncs without asking me the questions about network anymore. That may be what you want it to do, but I still experience issue #34 and since wizard does nothing I had to "ucoind config --hash <hash>" and so on for the other network properties. That finally got the node to work and I can see it in cutecoin, so I'm just reporting this for others to not have to manually do it that way. I've heard the fix to wizard not working was to install mongodb, which I did but that didn't make it work, even after going to their site and following all the steps to properly install it. And if mongodb needs to be installed for wizard to work, shouldn't it be in the wiki? I know it's early on and that was probably forgotten about when working on something else so it's not like everything is polished and ready for the public, I'm just a set of fresh eyes going through it for the first time, so I notice things like it never mentions you should set your port to something other than 9201, I chose 8999 because it's close and not being used according to a Wikipedia list of tcp and udp numbers.

Even after deleting the config and uninstalling ucoin and all the node stuff and reinstalling it, it still sync'd immediately without mentioning that upnp didn't work, how did it remember my answer? Is there a better way to uninstall than npm uninstall -g ucoin in case something from older versions is not being removed and now I'm seeing bugs new users wouldn't?

Thanks for your time.

**Comment by c-geek** [comment]
Thanks for your comment and the time you've spent trying to deploy a node by yourself.

You are right: #78 fixes the `ucoind wizard` command, which allows you to completely review and change your configuration. This fix will come with ucoin@0.11.5, so probably today (UTC+1).

You might also reset your configuration by using `ucoind reset config`, but as I tell you this, I notice this isn't working (#99). It will also be fixed for 0.11.5.

MongoDB is no more used by ucoin. I should remove that outdated information.

I guess you will be glad to use 0.11.5 to eventually help you change your config on will!

**Comment by c-geek** [comment]
Note for myself: this issue will be solved by updating documentation about MongoDB, plus adding a "Useful commands" note on the wiki.

**Comment by JBitD** [comment]
I can confirm after reinstalling ucoin it reports version 0.11.6; wizard works and I see the server in CuteCoin, so I must have answered its questions correctly.

**Comment by c-geek** [comment]
Since ucoin@0.12, the installation & init should be easier.

The documentation is here: https://github.com/ucoin-io/ucoin/wiki/Install-uCoin-node.
